name = "facebookdownbot"
main = "dist/worker.js" 
compatibility_date = "2024-11-18" 
compatibility_flags = ["nodejs_compat"]

[build]
command = "bun run build"
watch_dir = "src"

timeout = 30

[observability]
enabled = true
